# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aliddns < Formula
  desc "Aliyun ddns service"
  homepage "http://github.com/OpenIoTHub"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/OpenIoTHub/aliddns/releases/download/v0.0.8/aliddns_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "10495f5c192391845cc1926cfb19fdf1d20f29361a7fe9f45d3a516cd406076a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/OpenIoTHub/aliddns/releases/download/v0.0.8/aliddns_0.0.8_Linux_x86_64.tar.gz"
    sha256 "6d52e70dd08e235058a44c8d521f9ffba405eb4325cd1209c9069688792c6050"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/aliddns/releases/download/v0.0.8/aliddns_0.0.8_Linux_armv6.tar.gz"
    sha256 "4334ed191df7792ebb73296d9821ae5d355f3c8babd03f27f27123fa5fe8358d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/aliddns/releases/download/v0.0.8/aliddns_0.0.8_Linux_arm64.tar.gz"
    sha256 "da60beda173711f9a76006d5224985edc1ebfea1e220adf4e20c20d653dff0c2"
  end

  def install
    bin.install "aliddns"
  end

  test do
    system "#{bin}/aliddns -v"
  end
end
