# This file was generated by GoReleaser. DO NOT EDIT.
class GatewayGo < Formula
  desc "OpenIoTHub GateWay"
  homepage "http://github.com/OpenIoTHub"
  version "0.1.55"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/OpenIoTHub/gateway-go/releases/download/v0.1.55/gateway-go_0.1.55_Darwin_x86_64.tar.gz"
    sha256 "bcc8f587747904b3c3cbee3b40991c73efea18c20a55671bbd62a906880ed57f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/OpenIoTHub/gateway-go/releases/download/v0.1.55/gateway-go_0.1.55_Linux_x86_64.tar.gz"
      sha256 "f3a47fc59ac5a3d5675a36ec8cae97fd23d14b8568c5847cf76123909871e23e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OpenIoTHub/gateway-go/releases/download/v0.1.55/gateway-go_0.1.55_Linux_arm64.tar.gz"
        sha256 "f575660a6b43dfaab7e900a145ea825f37d1c520edbe8e69a668abe5d878d299"
      else
        url "https://github.com/OpenIoTHub/gateway-go/releases/download/v0.1.55/gateway-go_0.1.55_Linux_armv6.tar.gz"
        sha256 "d79c8df002700782e1fb97a64ddc32adfebbcc43374e82e0d3c71c73ab46035d"
      end
    end
  end

  def install
    bin.install "gateway-go"
  end

  test do
    system "#{bin}/gateway-go -v"
  end
end
