# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getip < Formula
  desc "OpenIoTHub get my public ip"
  homepage "http://github.com/OpenIoTHub"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.1/getip_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "f050bb812353e6e9d86b0bc7a5cdef0422e0976c787b30c037769160d3bd0323"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.1/getip_0.1.1_Linux_x86_64.tar.gz"
    sha256 "b14a081dd89b5a24d8496258bde7df633c473a4b08568c5fe889770d2ac8f655"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.1/getip_0.1.1_Linux_armv6.tar.gz"
    sha256 "d0732826313722b8513e6c5ff8df568fae390996b3797e32008a22befba203da"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.1/getip_0.1.1_Linux_arm64.tar.gz"
    sha256 "7017f6e1a4c9def6e5e6c46deda3d7936dea6a0685d7f8bdbf7124623b5553f8"
  end

  def install
    bin.install "getip"
  end

  test do
    system "#{bin}/getip -v"
  end
end
