# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getip < Formula
  desc "OpenIoTHub get my public ip"
  homepage "http://github.com/OpenIoTHub"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.3/getip_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "580028ce5fb3866257bd3b74e88434aa68cf52e5a4d9e85659da3249c7e9e48f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.3/getip_0.1.3_Linux_x86_64.tar.gz"
      sha256 "c9a7a3d82157894890d14b95c37585c0e3665d1b8ce7937c1d27cbdb0add7e88"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.3/getip_0.1.3_Linux_armv6.tar.gz"
      sha256 "b9dfb5cb859884d2f4186cc612809bd348abc91f4ecd4d2b9611eb96c2fa300b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenIoTHub/getip/releases/download/v0.1.3/getip_0.1.3_Linux_arm64.tar.gz"
      sha256 "1b9e8c931f8f1658812079288e8704b9e80679939ada326b8d7a97e41161660e"
    end
  end

  def install
    bin.install "getip"
  end

  test do
    system "#{bin}/getip -v"
  end
end
