# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnvifViewer < Formula
  desc "Onvif Camera Viewer"
  homepage "https://github.com/mDNSService/onvif-viewer"
  version "1.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.6/onvif-viewer_1.6_Darwin_x86_64.tar.gz"
      sha256 "495eded62cf7f227bae6a8358a8678ebb8103f998457430f2b96c89c14584275"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.6/onvif-viewer_1.6_Linux_x86_64.tar.gz"
      sha256 "5c995676f6efdb228b08a7630ad9f0334d067702c5035f0da3db1ff501e9100f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.6/onvif-viewer_1.6_Linux_armv6.tar.gz"
      sha256 "80daef92e44f15a8463d8e40aa00be0d916f5ca4cce1ba1d62d140dd943dcc48"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.6/onvif-viewer_1.6_Linux_arm64.tar.gz"
      sha256 "072e637e4885b79a36a70f137a703a966561a47946eb2864fc4e6aa9c9d8f198"
    end
  end

  def install
    bin.install "onvif-viewer"
  end

  test do
    system "#{bin}/onvif-viewer -v"
  end
end
