# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnvifViewer < Formula
  desc "Onvif Camera Viewer"
  homepage "https://github.com/mDNSService/onvif-viewer"
  version "1.3-debug"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.3-debug/onvif-viewer_1.3-debug_Darwin_x86_64.tar.gz"
    sha256 "f9ceb1980aeabecb4110e38048d056600bde27197757929c3c907d5f2cfa1e83"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.3-debug/onvif-viewer_1.3-debug_Linux_x86_64.tar.gz"
    sha256 "637aeebb9011f54dd1694b31a52fc9eda964b6ea27a1d8f364ecb8ee17c12fc3"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.3-debug/onvif-viewer_1.3-debug_Linux_armv6.tar.gz"
    sha256 "676a9aadefcfe9854be29f54186c16c3ea23f822e037ef6068dc2d2d98bd286d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mDNSService/onvif-viewer/releases/download/v1.3-debug/onvif-viewer_1.3-debug_Linux_arm64.tar.gz"
    sha256 "9f10d52f5bedc7807b6f83ea23b9ca518c3d1642bb540ce275e4db899bcbde2d"
  end

  def install
    bin.install "onvif-viewer"
  end

  test do
    system "#{bin}/onvif-viewer -v"
  end
end
