# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhicommR1Controler < Formula
  desc "Phicomm R1 Controler"
  homepage "https://github.com/IoTDevice/phicomm-r1-controler"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.5/phicomm-r1-controler_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "0c554cf084ef0b268a89a7d9d5c4fd3f6a04e7467862127a32b3783c4e501c5b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.5/phicomm-r1-controler_0.0.5_Linux_x86_64.tar.gz"
    sha256 "2333102976501b4b66b1f05ab62157f4f65cecf5cce2c9718de8198e04c3d4d0"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.5/phicomm-r1-controler_0.0.5_Linux_armv6.tar.gz"
    sha256 "baa291b05c090fdd450c1a3b86b09bb8ffd5257204ce06b3b5be87efa92fc4dc"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.5/phicomm-r1-controler_0.0.5_Linux_arm64.tar.gz"
    sha256 "8f91bb6b35bef6276ec364ea68d5b1ec55330414b87e522b4e23aef5fee97073"
  end

  def install
    bin.install "phicomm-r1-controler"
  end

  test do
    system "#{bin}/phicomm-r1-controler -v"
  end
end
