# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhicommR1Controler < Formula
  desc "Phicomm R1 Controler"
  homepage "https://github.com/IoTDevice/phicomm-r1-controler"
  version "0.0.22"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.22/phicomm-r1-controler_0.0.22_Darwin_x86_64.tar.gz"
    sha256 "116c86f6b2776b4b2935a5c7a5cebd453dcdcc8675fcbb347fa684ef329d9740"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.22/phicomm-r1-controler_0.0.22_Linux_x86_64.tar.gz"
    sha256 "612923f4f8e9ce9245cbc6b70766e166d51ca06482e97d88bd7bda2e2c9e795f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.22/phicomm-r1-controler_0.0.22_Linux_armv6.tar.gz"
    sha256 "a9ffec6ddeb335b9387d7d4cbe6bbcef8a92057466f84f4b537a05461a9198bd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/phicomm-r1-controler/releases/download/v0.0.22/phicomm-r1-controler_0.0.22_Linux_arm64.tar.gz"
    sha256 "c94888b0886742e9c025301783eb8227185f5bd850ce06eb0b341fcc44370805"
  end

  def install
    bin.install "phicomm-r1-controler"
  end

  test do
    system "#{bin}/phicomm-r1-controler -v"
  end
end
