# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerGo < Formula
  desc "OpenIoTHub Server"
  homepage "http://github.com/OpenIoTHub"
  version "1.2.3"

  on_macos do
    on_intel do
      url "https://github.com/OpenIoTHub/server-go/releases/download/v1.2.3/server-go_1.2.3_darwin_amd64.tar.gz"
      sha256 "54575380018e021635677332db421917d654dfd2b4ac172dcf8234d1828d2e6d"

      def install
        bin.install "server-go"
      end
    end
    on_arm do
      url "https://github.com/OpenIoTHub/server-go/releases/download/v1.2.3/server-go_1.2.3_darwin_arm64.tar.gz"
      sha256 "0ef2047093ac235d09ada0b3308e3d42f63cb521b148fe2c0eec6c0e21e4c591"

      def install
        bin.install "server-go"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OpenIoTHub/server-go/releases/download/v1.2.3/server-go_1.2.3_linux_amd64.tar.gz"
        sha256 "b64f45c1c6ba0c1a2ba4dc303426ceaa24bd80ffd1a35a0a5f9b36626d6b3461"

        def install
          bin.install "server-go"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/OpenIoTHub/server-go/releases/download/v1.2.3/server-go_1.2.3_linux_armv6.tar.gz"
        sha256 "e835ba364f0236b6ce507aa73d5068b4ae7b602e8e01791765e7ff81108714c9"

        def install
          bin.install "server-go"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OpenIoTHub/server-go/releases/download/v1.2.3/server-go_1.2.3_linux_arm64.tar.gz"
        sha256 "e457d93711f5a487ce6f4904456c9ccfdd2bf35402865589579535e4578e50ae"

        def install
          bin.install "server-go"
        end
      end
    end
  end

  test do
    system "#{bin}/server-go -v"
  end
end
