# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerGo < Formula
  desc "OpenIoTHub Server"
  homepage "http://github.com/OpenIoTHub"
  version "1.1.69"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.69/server-go_1.1.69_Darwin_x86_64.tar.gz"
    sha256 "3da19380e6cf643ea05f4c5eb219dd0b277cb430d60032917b958f4be39b85be"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.69/server-go_1.1.69_Darwin_arm64.tar.gz"
    sha256 "84d2bf8b95b7c35b1e6f258db54e36179d41de59490c4be3fe00e1c6d6781ccd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.69/server-go_1.1.69_Linux_x86_64.tar.gz"
    sha256 "0557b8bd99655aa72be39a88955274ce4f65cc526c05af1c7aca78944f549552"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.69/server-go_1.1.69_Linux_armv6.tar.gz"
    sha256 "61dad8d43e66152aaad9d4e2ea6adff2377ed1f7af99ed70a03657f823782e21"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.69/server-go_1.1.69_Linux_arm64.tar.gz"
    sha256 "0cc8c216a8848994416f992aed6448857b86a9c85f92ce0639a9060593057765"
  end

  def install
    bin.install "server-go"
  end

  test do
    system "#{bin}/server-go -v"
  end
end
