# This file was generated by GoReleaser. DO NOT EDIT.
class ServerGo < Formula
  desc "OpenIoTHub Server"
  homepage "http://github.com/OpenIoTHub"
  version "1.1.23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.23/server-go_1.1.23_Darwin_x86_64.tar.gz"
    sha256 "309ed526402e48af44e69712b2b1387fb5861cf1e6883105ca749a1ec8350857"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.23/server-go_1.1.23_Linux_x86_64.tar.gz"
      sha256 "c2baab95bf8d9d8ddb69c2d49d434e553165614c9c4df6c640ae44eb9454c48d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.23/server-go_1.1.23_Linux_arm64.tar.gz"
        sha256 "2cf3fdf0a567c19c62d22f184c5884c134fa9780e281240f3b1cc953da34e874"
      else
        url "https://github.com/OpenIoTHub/server-go/releases/download/v1.1.23/server-go_1.1.23_Linux_armv6.tar.gz"
        sha256 "bdb384c6b262ecd945389ad9e5e7ead31d7df087a9e1551f2ad476ed57993ff2"
      end
    end
  end

  def install
    bin.install "server-go"
  end

  test do
    system "#{bin}/server-go -v"
  end
end
