# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeroconf < Formula
  desc "mdns service finder"
  homepage "https://github.com/IoTDevice/zeroconf"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.9/zeroconf_0.1.9_Darwin_x86_64.tar.gz"
    sha256 "c6116ac39544246bc701ffe8f79ecb12e41ec5f9370fee22b4f9a372e18e2d5e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.9/zeroconf_0.1.9_Linux_x86_64.tar.gz"
    sha256 "559bfc6d38dc8b7f63710c8cc17cc348df849379684ee0cc79530512fe5a4670"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.9/zeroconf_0.1.9_Linux_armv6.tar.gz"
    sha256 "b45c1dc761212664a48e19987274657f16ef8fa5e275daaa325c297e2c650eb5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.9/zeroconf_0.1.9_Linux_arm64.tar.gz"
    sha256 "7c6f0cdf684436ead46e911a88bb2400c6689138d6a91a7b414b96e1ea9949d5"
  end

  def install
    bin.install "zeroconf"
  end

  test do
    system "#{bin}/mdns -v"
  end
end
