# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeroconf < Formula
  desc "mdns service finder"
  homepage "https://github.com/IoTDevice/zeroconf"
  version "0.1.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.8/zeroconf_0.1.8_Darwin_x86_64.tar.gz"
    sha256 "c42f70c08254d565d426fd0aa772ea5c1da261002cddd17d90d6cdad00d88503"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.8/zeroconf_0.1.8_Linux_x86_64.tar.gz"
    sha256 "6389a287a4f476978156d45fcdae78d064614f45d13c26bf64bf4f1a788a1ef8"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.8/zeroconf_0.1.8_Linux_armv6.tar.gz"
    sha256 "ce77a123312447ada11e139ac4ce33c77361f8929ab9d4d326a8eb1f0664c28b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/IoTDevice/zeroconf/releases/download/v0.1.8/zeroconf_0.1.8_Linux_arm64.tar.gz"
    sha256 "df688d93021b9b19c07eadae90aec1507c49c3583297586051fd2d99ea7f05db"
  end

  def install
    bin.install "zeroconf"
  end

  test do
    system "#{bin}/mdns -v"
  end
end
